### ISSUE TITLE
Error on updating to 1.20

### ISSUE THREAD

**Issue by karl007** [TheRemote/Legendary-Java-Minecraft-Geyser-Floodgate#23]
Hi.

I got this error if I change my `Version` param in the docker-compose from `1.19.4` to `1.20`:

```
minecraft        | Updating to most recent paperclip version ...
minecraft        | /scripts/start.sh: line 142: {"error":"Version not found."} + 0: syntax error: operand expected (error token is "{"error":"Version not found."} + 0")
```

What is weird, that if i execute the part of the start.sh manual, everything seems OK:
```bash
$ Version=1.20
$ BuildJSON=$(curl --no-progress-meter -H "Accept-Encoding: identity" -H "Accept-Language: en" -L -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4.212 Safari/537.36" https://papermc.io/api/v2/projects/paper/versions/$Version)
$ Build=$(echo "$BuildJSON" | rev | cut -d, -f 1 | cut -d']' -f 2 | cut -d'[' -f 1 | rev)

$ echo $BuildJSON
{"project_id":"paper","project_name":"Paper","version":"1.20","builds":[1,2,3,4,5,6,7,8,9,10]}

$ echo $Build
10
```

Anyone has the same Problem? Any suggestions?
 

I tried to completly rebuild the container:
```bash
docker-compose build --no-cache minecraftbe; docker-compose up -d --force-recreate minecraftbe
```

And here is my docker-compose part:
```yml
services:
  minecraftbe:
    container_name: minecraft
    image: 05jchambers/legendary-minecraft-geyser-floodgate:latest
    restart: "unless-stopped"
    ports:
      - 25565:25565
      - 19133:19132
      - 19133:19132/udp
    volumes:
      - ./minecraft:/minecraft
    stdin_open: true # docker run -i
    tty: true # docker run -t
    # Environment variables
    environment:
      Port: "25565"
      BedrockPort: "19132"
      TZ: "Europe/Berlin" # Timezone
      BackupCount: 20 # Number of rolling backups to keep
      MaxMemory: 2048 # Maximum memory usage for Java
      Version: 1.20 # Use custom version
      NoBackup: "backups,plugins/dynmap/web/tiles" # Optional folder to skip during backups
      #NoPermCheck: "Y" # Optional flag to skip permissions check
      #QuietCurl: "Y" # Optional flag to reduce curl log output by suppressing progress meter
```
