### ISSUE TITLE
`NoBackup` option not working

### ISSUE THREAD

**Issue by KurtPreston** [TheRemote/Legendary-Java-Minecraft-Geyser-Floodgate#45]
Hello, thank you for this image! Really great foundation for a Minecraft server. I am having issues getting the `NoBackup` environment variable to work. Here is an excerpt from my `docker-compose.yml` file:

```yaml
services:
  creative:
    image: 05jchambers/legendary-minecraft-geyser-floodgate:latest
    stdin_open: ${USE_TTY}
    tty: ${USE_TTY}
    volumes:
      - ${CREATIVE_DATA_DIR}:/minecraft
    ports:
      - "${CREATIVE_BEDROCK_PORT}:${INTERNAL_BEDROCK_PORT}"
      - "${CREATIVE_BEDROCK_PORT}:${INTERNAL_BEDROCK_PORT}/udp"
      - "${CREATIVE_JAVA_PORT}:${INTERNAL_JAVA_PORT}"
    environment:
      - Version=1.21.4
      - NoBackup="plugins,libraries"
    user: "${DOCKER_USER}"
```

However, on startup, it seems to try to back-up my `plugins` and `libraries` folders regardless. Any idea what I might be doing wrong?

Is there any way to disable auto-backup altogether? I have a separate back-up process, and would love to just turn off the feature if possible.

**Comment by KurtPreston** [comment]
My mistake, it was misuse of quotes when setting `NoBackup`.

It should instead be
```yaml
services:
  creative:
    environment:
      - NoBackup=plugins,libraries
```
