### ISSUE TITLE
Failed to varify username

### ISSUE THREAD

**Issue by TonySerpofski** [TheRemote/Legendary-Java-Minecraft-Geyser-Floodgate#50]
Ive added ONLINE_MODE: "FALSE" which normally does the trick but its not working. I cant join the server thats running.

```
services:
  minecraft:
    image: 05jchambers/legendary-minecraft-geyser-floodgate:latest
    container_name: minecraft-server
    environment:
      EULA: "TRUE"  # Accept the Minecraft EULA
      TYPE: "PAPER"  # Use Paper for better performance and plugin support
      # You can set other environment variables if necessary:
      # - MaxMemory: "2048"  # Optional: Set the max memory in MB
      # - Version: "1.17.1"  # Optional: Specify the Minecraft version
      # - TZ: "America/Denver"  # Optional: Set the timezone
      # - BackupCount: "20"  # Optional: Set the number of backups retained
      # - QuietCurl: "Y"  # Optional: Suppress curl output     
      ONLINE_MODE: "FALSE"

    ports:
      - "25565:25565"  # Java Edition port
      - "19132:19132/udp"  # Bedrock Edition port (UDP)
      - "19132:19132"  # Bedrock Edition port (TCP)
    volumes:
      - minecraft_data:/minecraft  # Mount Docker volume for persistent data
    restart: unless-stopped
    networks:
      - minecraft_net

volumes:
  minecraft_data:  # Named volume to persist server data
    driver: local

networks:
  minecraft_net:  # Create a custom network for the server
    driver: bridge
```
